Improving styling to match HomeAssistant entities card
esphome/esphome-webserver pull request #49
Opened 2023-11-28 01:11 UTC by afarago

This PR is a styling upgrade to match the styling of HomeAssistant entities card.

* icons using the standard HA iconset via on demand and thus with a graceful degradation (no icon shown if WAN is down)
* group by entity_categories
* instead of table use div and grid/flex layouts
* added uptime based on ping value
* color picker for rgb lights
* Tag column hidden on web view
* update icon to use the 

Icons and entity_categories functionally needs matching PR in esphome/web_server component - though the two still work in the previous way without the other.

Not sure about coding standards, or formatting in this repo. Please comment and help me with a pointer if styling changes are needed. 

Related discord discussion - https://discord.com/channels/429907082951524364/1177062706340171807

2023-11-28 09:14 UTC, afarago commented
Pull request in [esphome](https://github.com/esphome/esphome): esphome/esphome#5854

2023-12-22 03:00 UTC, jesserockz requested changes
I just have one comment to make as I am not very familiar with typescript/lit and frontend in general

2023-12-22 10:44 UTC, afarago commented on .vscode/tasks.json
OK, thanks for catching this mistake.

2023-12-22 11:40 UTC, afarago commented
I believe I have marked the requested change resolved, yet am a bit unsure over the github status.
Please let me know if there are any pending actions on my side.

2024-01-18 11:23 UTC, DocBrown101 commented
Can I help with the review, or what exactly is still missing here?

2024-02-23 07:05 UTC, kevireilly commented
@DocBrown101 it has been discussed in the discord [thread](https://discord.com/channels/429907082951524364/1177062706340171807) that this work would likely be best represented as v3 instead of modifying v2. However, in order to facilitate that, there are some structural changes required via #53.

Once that lands, this work can be rebased and restructured using a new v3 package and then we should be clear for lift off on merging, deploying, and beta testing with those tuned in.

2024-03-06 09:51 UTC, kevireilly commented
This pull request can probably be closed as #54 supersedes it.

2024-03-18 18:49 UTC, closed without merging

2024-03-19 07:09 UTC, DocBrown101 commented
From which version will it be available as v3 in an esphome release?